### ISSUE TITLE
Exclude disused bus stops of the list of no name bus stops

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#1]
- Exclude bus stop who have the key value disused=yes (or disused:highway=bus_stop) in the script https://github.com/nlehuby/OSM_snippets/blob/master/kml-todo/kml_generator.py#L31 and then update the [article about this script]( https://nlehuby.5apps.com/mapsme-arrets-bus-sans-nom.html).

Notes:
- [A real example of a disused bus stop, in Paris](http://www.openstreetmap.org/node/2271679202)
- 17 [disused:highway=bus_stop](https://taginfo.openstreetmap.fr/tags/disused%3Ahighway=bus_stop) in France

**Comment by nlehuby** [comment]
Hello,

merci pour le feedback (et bravo pour avoir trouvé le code source ;) )

Je ne comprends pas trop à quoi ça correspond : 
* si l'arrêt de bus n'existe plus sur le terrain, on peut le supprimer
* si ce n'est plus un arrêt de bus, on peut le requalifier (amenity=taxi ou amenity = shelter ou amenity=car_sharing, etc en fonction du cas)
Dans quel cas d'usage on utilise ce tag `disused` pour un arrêt de bus ?

**Comment by Manu1400** [comment]
http://www.openstreetmap.org/node/2271679202 -> arrêt de bus entouré de plastique, volontairement masqué, probablement trop proche de l'Élysée. Il existe donc encore concrètement sur le terrain (et peut donc être techniquement réactivé par le gestionnaire d'un jour à l'autre) mais est bien "_disused_".

**Comment by nlehuby** [comment]
ok. Merci, cas intéressant !

la requête overpass est  corrigée, et les kml à jour sont dispo à la même adresse.
