### ISSUE TITLE
Proposition : liste des notes OSM (non résolues) à propos d'un arrêt de bus

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#10]
Fournir une liste des notes OSM actuellement non résolues qui parlent d'un ou de plusieurs arrêts de bus.

Technique : 
- Extraction des notes pertinentes par expressions ("bus stop")

Exemple de note concernée : https://www.openstreetmap.org/note/997788#map=17/48.76005/2.36215&layers=N

**Comment by nlehuby** [comment]
Cet outil fait le job pour ce besoin : https://ent8r.github.io/NotesReview/expert/?query=%23busfr&limit=100 :tada:
