### ISSUE TITLE
actualisation des données quotidiennes

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#16]
Afin de mieux voir les lignes restantes à associer, il serait intéressant d'avoir une automatisation de la mise à jour de la liste des lignes à associer (et donc des données).

**Comment by nlehuby** [comment]
Que veux-tu dire ?
La liste des lignes d'OSM, dont les lignes restant à associer, sont mises à jour régulièrement sur https://ref-lignes-stif.5apps.com/ et dans ce repo. Au dernières nouvelles, il en reste 32 sur 683.
