### ISSUE TITLE
retirer (de la liste) la ligne de bus autonome

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#17]
Filtre : "note=autonomous bus" pour retirer la relation http://www.openstreetmap.org/relation/7434957

**Comment by nlehuby** [comment]
je ne suis pas fan ... Ce qu'on veut exclure, ce sont les lignes qui ne sont pas sous la responsabilité du STIF, et c'est pas parce que c'est autonome que c'est le cas (le métro 14 est bien autonome par exemple :p)

Tu peux ajouter `network=local` dessus plutôt. Il y a déjà un filtre sur ce tag, pour filtrer les navettes municipale pour aller au marché, etc
