### ISSUE TITLE
Filtrer la relation Eurostar : Marseille − Londres

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#19]
Cette relation est visible dans https://ref-lignes-stif.5apps.com/index.html

Solution envisagée : Exclure les relations ayant la clé-valeur : service=international (qui est utilisée dans la https://www.openstreetmap.org/relation/8522993 ) et qui est aussi utilisée pour la relation EN 452/453 Moskva - Paris.

**Comment by nlehuby** [comment]
fait ici : https://github.com/Jungle-Bus/ref-fr-STIF/commit/4099fe235d928e462ee320ab56d342e7a8648977 

merci :+1:
