### ISSUE TITLE
Filter pédibus

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#21]
(trajet à pied de rammage scolaire) https://ref-lignes-stif.5apps.com/line.html?osm_relation=9323686&line_code=K

`Réseau : Pédibus`

**Comment by nlehuby** [comment]
Ravie que tu l'aies vue passer ;)

Filtrer sur le réseau va fonctionner mais ce n'est pas vraiment ce qu'on recherche, je préfèrerais qu'on arrive à exclure toutes les lignes de pédibus, vu que le STIF n'en a pas du tout dans ses données.
Mais il faut au préalable clarifier la bonne manière de cartographier une ligne de pédibus dans OSM ...
À suivre sur la liste [transport](https://listes.openstreetmap.fr/wws/arc/transport) ;)
