### ISSUE TITLE
[ref-lignes tool] Filter route_master=bicycle

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#3]
Filtrer pour retirer de l'outil https://ref-lignes-stif.5apps.com/ la relation "Route Paris-Prague" de type bicycle.

**Comment by nlehuby** [comment]
ainsi que la batobus.

**Comment by Manu1400** [comment]
pour le batobus, on peut filtrer par le tag route_master, histoire que je puisse faire évoluer ses autres tags sans avoir à changer le filtrage.
