### ISSUE TITLE
[STIF-to-OSM] Code STIF non trouvé (relation RER E)

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#6]
1/ Clic sur la ligne concernant une nouvelle relation (RER E) dans https://ref-lignes-stif.5apps.com/
2/ Chargement de la page https://ref-lignes-stif.5apps.com/line.html?osm_relation=7271953&line_code=E#
3/ Bouton "Proposition de ligne suivante" jusqu'à obtenir la 6ème : Haussmann Saint-Lazare - Gare de Chelles Gournay
4/ Bouton "Associer cette ligne"

Attendu : 
Relation OSM avec le code STIF de la ligne ajoutée et affichage d'une page openstreetmap.org

Observé : 
- Aucun effet.
- log en console :  "impossible de trouver le code à envoyer à OSM" (à chaque clic sur le bouton "Associer cette ligne"

Navigateur : Google Chrome, extensions non actives, navigation avec cookies

**Comment by nlehuby** [comment]
Hello,

Merci pour le feedback.
C'est un bug connu, reproductible sur les lignes qui peuvent avoir des bus de substitution.


Le 25 mai 2017 21:40:17 GMT+02:00, Manu1400 <notifications@github.com> a écrit :
>1/ Clic sur la ligne concernant une nouvelle relation (RER E) dans
>https://ref-lignes-stif.5apps.com/
>2/ Chargement de la page
>https://ref-lignes-stif.5apps.com/line.html?osm_relation=7271953&line_code=E#
>3/ Bouton "Proposition de ligne suivante" jusqu'à obtenir la 6ème :
>Haussmann Saint-Lazare - Gare de Chelles Gournay
>4/ Bouton "Associer cette ligne"
>
>Attendu : 
>Relation OSM avec le code STIF de la ligne ajoutée et affichage d'une
>page openstreetmap.org
>
>Observé : 
>- Aucun effet.
>- log en console :  "impossible de trouver le code à envoyer à OSM" (à
>chaque clic sur le bouton "Associer cette ligne"
>
>Navigateur : Google Chrome, extensions non actives, navigation avec
>cookies
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nlehuby/OSM_snippets/issues/6

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by nlehuby** [comment]
c'est corrigé :)
