### ISSUE TITLE
Avoir une liste des lignes de bus (STIF) non présentes dans OSM

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#7]
Connaitre les 1 300 lignes de bus non présentes, afin de pouvoir les ajouter.

**Comment by nlehuby** [comment]
Hello,

je pense que c'est encore un peu tôt. Si on fait ça, j'ai peur qu'on tombe dans un des deux pièges suivants :
* la création de relations en doublon parce qu'on n'a pas vu qu'elle existait déjà mais avec des propriétés (nom, opérateur, réseau) mal voire pas du tout renseignées
* la création de relations vides parce qu'on n'a pas trouvé d'objets déjà dans OSM à mettre dedans

Pour le moment, je privilégie trois approches complémentaires : 
* passer systématiquement sur les arrêts de bus non membres d'une relation. Cf [mon article de blog](https://nlehuby.5apps.com/mapsme-arrets-bus-ameliorer-qualite.html). En faisant ça, on tombe régulièrement sur des cas où les relations routes (puis route_master) restent à créer
* passer sur toutes les relations routes non membres d'une relation route_master. D'après mes estimations de la semaine dernière, il en reste encore 361 en idf. J'ai prévu une analyse Osmose sur le sujet pour les mettre plus facilement en visibilité de tous
* effectuer une vérification systématique de toutes les lignes, variantes et arrêts d'un réseau et en profiter pour créer/mettre à jour l'état sur le wiki. J'ai commencé pour [le réseau Pep's](https://wiki.openstreetmap.org/wiki/WikiProject_France/Bus_Pep%27s#Transporteur_AMV) par exemple. C'est l'occasion de créer les relations manquantes et d'identifier les arrêts restant à cartographier, mais c'est très long à faire. Pour encore plus de challenge, privilégier les réseaux de banlieue éloignée :p 

Et bien sûr, en parallèle, il y a encore du travail de mise en qualité des tags name, operator et network sur les route et route_master, pour éviter toute ambiguité sur ce que la relation représente (idem, analyse Osmose dans les tuyaux)

**Comment by nlehuby** [comment]
Voici une analyse Osmose liste des relations route non incluses dans des relations route_master : http://osmose.openstreetmap.fr/fr/errors/?item=1260&class=4&country=france_ile_de_france

Cela correspond à des lignes à créer que l'on peut ajouter facilement.

**Comment by Manu1400** [comment]
J'aurai de nouveau besoin de la liste des lignes non associées à OSM.

Un grand nombre de lignes a été associé désormais.

Quand une ligne apparait dans OSM, il faut parfois essayer de trouver cette ligne dans le [tableau du STIF](https://opendata.stif.info/explore/dataset/referentiel-des-lignes-stif/table/).
Or il arrive que cette ligne ne soit pas présente dans ce tableau.

Donc un simple tableau avec les lignes non associées dans OSM serait utile, régulièrement, pour justement associer les lignes.

**Comment by nlehuby** [comment]
Hello,

j'ai ajouté une étape au script pour extraire les lignes opendata pour lesquelles il n'y a pas de ligne dans OSM : https://github.com/Jungle-Bus/ref-fr-STIF/blob/gh-pages/data/osm_missing_lines.csv

EDIT: ce fichier (et les autres aussi) est maintenant mis à jour quotidiennement sur la base des données OSM de la veille et des dernières données GTFS dispo.
