### ISSUE TITLE
Proposition : Indiquer les relations "en doublon"

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#8]
Indiquer quand une relation est en doublon dans OpenstreetMap (même référence STIF qu'une autre relation route master)

Exemple : 
Ref STIF identique (287191100:191-100) au niveau de deux relations OSM : 
- 6867537
- 6867541

**Comment by nlehuby** [comment]
Bonne idée.
Ça sera plutôt dans Osmose du coup.

**Comment by nlehuby** [comment]
Désolée du délai, j'avais complètement zappé :(
c'est ajouté dans l'analyse Osmose ; aujourd'hui, il y en a 7 : http://osmose.openstreetmap.fr/fr/errors/?source=28482&item=8042&class=1
