### ISSUE TITLE
Exclure les navettes commerciales existantes en Ile de France

### ISSUE THREAD

**Issue by Manu1400** [nlehuby/OSM_snippets#9]
Exclusion possible, à titre préventif, des navettes suivantes : 

- Magical Shuttle. [1]
- navettes "Ikea"

Sources : 
[1] : https://fr.wikipedia.org/wiki/Orly-Ouest_(Orlyval) et https://fr.wikipedia.org/wiki/Lignes_de_bus_Mobilien_100

**Comment by nlehuby** [comment]
Bonne idée, mais à moins que tu n'aies déjà commencé à les cartographier, je préfère attendre qu'elles apparaissent pour les filtrer.
